
preset: laravel

enabled:
- alpha_ordered_imports
- simplified_null_return

disabled:
- length_ordered_imports

finder:
  exclude:
  - "tests"
  - "node_modules"
  - "storage"
  - "vendor"
  name:
  - "*.php"
  not-name:
  - "*.blade.php"
  - "FunctionalTester.php"
  - "UnitTester.php"
